name: Lab 4 CI

on:
  push:
  workflow_dispatch:

jobs:
  lab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say hello
        run: echo "Hello from GitHub Actions!"

      - name: Check files
        run: ls -la
